/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.programadorroni.gestor_multas;

import java.awt.*;
import java.io.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.programadorroni.gestor_multas.Multa;
import com.programadorroni.gestor_multas.Nodo;
import com.programadorroni.gestor_multas.ListaDobleMulta;

/**
 * @author isaia
 */
    public class PanelPrincipal extends javax.swing.JPanel {
       
        private ListaDobleMulta listaMultas;
        private int contadorID = 1;

        public PanelPrincipal() {
        initComponents();
        listaMultas = new ListaDobleMulta();
    }
        
    private void Buscar_Fch_1ActionPerformed(java.awt.event.ActionEvent evt) {
         JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de texto", "txt"));
    int resultado = fileChooser.showOpenDialog(this);

    if (resultado == JFileChooser.APPROVE_OPTION) {
        File archivoActual = fileChooser.getSelectedFile();
        cargarDesdeArchivo(archivoActual);
    }
    }
    
    private void cargarDesdeArchivo(File archivo) {
        listaMultas.limpiar();

        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(";");
                if (datos.length == 7) {
                    int id = Integer.parseInt(datos[0].trim());
                    String placa = datos[1].trim();
                    String fecha = datos[2].trim();
                    String departamento = datos[3].trim();
                    String descripcion = datos[4].trim();
                    double monto = Double.parseDouble(datos[5].trim());
                    String estado = datos[6].trim();

                    Multa multa = new Multa(id, placa, fecha, departamento, descripcion, monto, estado);
                    listaMultas.insertarOrdenado(multa);
                }
            }

            mostrarEnTabla(listaMultas.obtenerDatos());
        } catch (IOException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarEnTabla(Object[][] datos) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"BOLETA", "Placa", "Fecha", "Departamento", "Descripción", "Monto", "Estado"});
        for (Object[] fila : datos) {
            modelo.addRow(fila);
        }
        Tabla_Multa_1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Primer_Panel = new javax.swing.JPanel();
        Panel_Llenado_1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Descargar_Fich_1 = new javax.swing.JButton();
        Asignar_Multa = new javax.swing.JButton();
        Nuevo_Doc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Multa_1 = new javax.swing.JTable();
        EscribirBus = new javax.swing.JTextField();
        Buscar_Placa_1 = new javax.swing.JButton();
        Eliminar_1 = new javax.swing.JButton();
        Ticket_1 = new javax.swing.JButton();
        MULTAS = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        TRASPASOS = new javax.swing.JButton();
        RESUMEN = new javax.swing.JButton();
        VEHICULOS = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Usuario = new javax.swing.JButton();
        User_Indicator = new javax.swing.JLabel();
        Barra = new javax.swing.JButton();
        Desplegable = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Buscar_Fch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        Primer_Panel.setBackground(new java.awt.Color(17, 34, 61));

        Panel_Llenado_1.setBackground(new java.awt.Color(255, 204, 0));

        Descargar_Fich_1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Descargar_Fich_1.setText("GUARDAR");
        Descargar_Fich_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Descargar_Fich_1ActionPerformed(evt);
            }
        });

        Asignar_Multa.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        Asignar_Multa.setText("ASIGNAR MULTA");
        Asignar_Multa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asignar_MultaActionPerformed(evt);
            }
        });

        Nuevo_Doc.setText("+");
        Nuevo_Doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo_DocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nuevo_Doc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Asignar_Multa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Descargar_Fich_1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Asignar_Multa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Nuevo_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Descargar_Fich_1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        Tabla_Multa_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "BOLETA", "PLACA", "FECHA", "DEPARTAMENTO", "DESCRIPCION", "MONTO", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_Multa_1.setEnabled(false);
        Tabla_Multa_1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla_Multa_1);
        if (Tabla_Multa_1.getColumnModel().getColumnCount() > 0) {
            Tabla_Multa_1.getColumnModel().getColumn(0).setResizable(false);
            Tabla_Multa_1.getColumnModel().getColumn(1).setResizable(false);
            Tabla_Multa_1.getColumnModel().getColumn(2).setResizable(false);
            Tabla_Multa_1.getColumnModel().getColumn(3).setResizable(false);
            Tabla_Multa_1.getColumnModel().getColumn(4).setResizable(false);
            Tabla_Multa_1.getColumnModel().getColumn(5).setResizable(false);
            Tabla_Multa_1.getColumnModel().getColumn(6).setResizable(false);
        }

        EscribirBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirBusActionPerformed(evt);
            }
        });

        Buscar_Placa_1.setBackground(new java.awt.Color(255, 204, 0));
        Buscar_Placa_1.setIcon(new javax.swing.ImageIcon("C:\\Users\\isaia\\Documents\\NetBeansProjects\\Gestor_Multas\\Iconos\\icons8-buscar-24.png")); // NOI18N
        Buscar_Placa_1.setBorder(null);
        Buscar_Placa_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_Placa_1ActionPerformed(evt);
            }
        });

        Eliminar_1.setBackground(new java.awt.Color(255, 204, 0));
        Eliminar_1.setIcon(new javax.swing.ImageIcon("C:\\Users\\isaia\\Documents\\NetBeansProjects\\Gestor_Multas\\Iconos\\icons8-eliminar-24.png")); // NOI18N
        Eliminar_1.setBorder(null);
        Eliminar_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_1ActionPerformed(evt);
            }
        });

        Ticket_1.setText("TICKET");
        Ticket_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ticket_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_Llenado_1Layout = new javax.swing.GroupLayout(Panel_Llenado_1);
        Panel_Llenado_1.setLayout(Panel_Llenado_1Layout);
        Panel_Llenado_1Layout.setHorizontalGroup(
            Panel_Llenado_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Llenado_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Llenado_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(Panel_Llenado_1Layout.createSequentialGroup()
                        .addComponent(Buscar_Placa_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EscribirBus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(992, 992, 992)
                        .addComponent(Eliminar_1)
                        .addGap(18, 18, 18)
                        .addComponent(Ticket_1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Panel_Llenado_1Layout.setVerticalGroup(
            Panel_Llenado_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Llenado_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Llenado_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ticket_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Eliminar_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EscribirBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar_Placa_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        MULTAS.setText("MULTAS");
        MULTAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MULTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTASActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Gestor de Multas");

        TRASPASOS.setText("TRASPASOS");
        TRASPASOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRASPASOSActionPerformed(evt);
            }
        });

        RESUMEN.setText("RESUMEN");

        VEHICULOS.setText("VEHICULOS");
        VEHICULOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VEHICULOSActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        Usuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\isaia\\Documents\\NetBeansProjects\\Gestor_Multas\\Iconos\\icons8-usuario-16.png")); // NOI18N
        Usuario.setBorder(null);
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        User_Indicator.setText("Roni Ruiz");

        Barra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Barra.setText("=");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(User_Indicator, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario)
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(User_Indicator)
                    .addComponent(Barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Desplegable.setBackground(new java.awt.Color(31, 49, 73));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGOTIPO");

        javax.swing.GroupLayout DesplegableLayout = new javax.swing.GroupLayout(Desplegable);
        Desplegable.setLayout(DesplegableLayout);
        DesplegableLayout.setHorizontalGroup(
            DesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesplegableLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        DesplegableLayout.setVerticalGroup(
            DesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesplegableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agregar Fichero Existente");

        Buscar_Fch.setBackground(new java.awt.Color(17, 34, 61));
        Buscar_Fch.setIcon(new javax.swing.ImageIcon("C:\\Users\\isaia\\Documents\\NetBeansProjects\\Gestor_Multas\\Iconos\\icons8-folder-48.png")); // NOI18N
        Buscar_Fch.setBorder(null);
        Buscar_Fch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_FchActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tiempo de Carga");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Primer_PanelLayout = new javax.swing.GroupLayout(Primer_Panel);
        Primer_Panel.setLayout(Primer_PanelLayout);
        Primer_PanelLayout.setHorizontalGroup(
            Primer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Primer_PanelLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(MULTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(TRASPASOS)
                .addGap(250, 250, 250)
                .addComponent(VEHICULOS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(RESUMEN)
                .addGap(146, 146, 146))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Primer_PanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Primer_PanelLayout.createSequentialGroup()
                .addComponent(Desplegable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Primer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Primer_PanelLayout.createSequentialGroup()
                        .addGroup(Primer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Primer_PanelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Primer_PanelLayout.createSequentialGroup()
                                .addComponent(Buscar_Fch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(Panel_Llenado_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Primer_PanelLayout.setVerticalGroup(
            Primer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Primer_PanelLayout.createSequentialGroup()
                .addGroup(Primer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Primer_PanelLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addGroup(Primer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MULTAS)
                            .addComponent(TRASPASOS)
                            .addComponent(VEHICULOS)
                            .addComponent(RESUMEN))
                        .addGap(75, 75, 75)
                        .addGroup(Primer_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Buscar_Fch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Panel_Llenado_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Desplegable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Primer_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Primer_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void MULTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTASActionPerformed
        // TODO add your handling code here:
        Primer_Panel.removeAll();                   // Limpia lo que haya en Primer_Panel
    Primer_Panel.setLayout(new BorderLayout()); // Ajusta el layout para que PanelMulta ocupe todo el espacio

    PanelMulta panelMulta = new PanelMulta();   // Crear instancia del PanelMulta (asegúrate de tener su constructor sin args)
    
    Primer_Panel.add(panelMulta, BorderLayout.CENTER);
    Primer_Panel.revalidate();  // Refrescar la UI
    Primer_Panel.repaint();
    }//GEN-LAST:event_MULTASActionPerformed
                
    private void actualizarTabla(JTable tabla) {
    Object[][] datos = listaMultas.obtenerDatos();
    String[] columnas = {"BOLETA", "PLACA", "FECHA", "DEPARTAMENTO", "DESCRIPCIÓN", "MONTO", "ESTADO"};
    tabla.setModel(new DefaultTableModel(datos, columnas));
}
    public void cargarArchivoConBoleta(File archivo) {
      listaMultas.limpiar();

    try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
        String linea;
        int id = 1;
        while ((linea = br.readLine()) != null) {
            String[] partes = linea.split(",");
            if (partes.length == 6) {
                Multa multa = new Multa(id++, partes[0], partes[1], partes[2], partes[3],
                                        Double.parseDouble(partes[4]), partes[5]);
                listaMultas.insertarOrdenado(multa);
            }
        }
    } catch (IOException | NumberFormatException e) {
        e.printStackTrace();
    }

    actualizarTabla(Tabla_Multa_1);
}
    
    private void refrescarTabla() {
    Object[][] datos = listaMultas.obtenerDatos();
    String[] columnas = {"BOLETA", "PLACA", "FECHA", "DEPARTAMENTO", "DESCRIPCIÓN", "MONTO", "ESTADO"};
    DefaultTableModel modelo = new DefaultTableModel(datos, columnas);
    Tabla_Multa_1.setModel(modelo);
    }
    
    private void Nuevo_DocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo_DocActionPerformed
        // TODO add your handling code here:
      JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Crear nuevo documento");

    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();

        // Asegurar extensión .txt
        if (!fileToSave.getName().toLowerCase().endsWith(".txt")) {
            fileToSave = new File(fileToSave.getAbsolutePath() + ".txt");
        }

        try {
            if (!fileToSave.exists()) {
                boolean creado = fileToSave.createNewFile();
                if (creado) {
                    JOptionPane.showMessageDialog(this, "Archivo creado exitosamente: " + fileToSave.getName());

                    // Limpiar la lista doble y reiniciar ID
                    listaMultas.limpiar();
                    contadorID = 1;

                    // Refrescar tabla vacía
                    refrescarTabla();

                    // Opcional: guardar el archivo en una variable si deseas usarlo más tarde
                    // archivoActual = fileToSave;
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo crear el archivo.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "El archivo ya existe.");
            }
        } catch (IOException e) {
            e.printStackTrace(); // Muestra error en consola
            JOptionPane.showMessageDialog(this, "Error al crear el archivo: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_Nuevo_DocActionPerformed

    private void Asignar_MultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asignar_MultaActionPerformed
        // TODO add your handling code here:
        JTextField placa = new JTextField();
    JTextField fecha = new JTextField();
    JTextField departamento = new JTextField();
    JTextField descripcion = new JTextField();
    JTextField monto = new JTextField();
    JTextField estado = new JTextField();

    JPanel panel = new JPanel(new GridLayout(0, 1));
    panel.add(new JLabel("PLACA:")); panel.add(placa);
    panel.add(new JLabel("FECHA:")); panel.add(fecha);
    panel.add(new JLabel("DEPARTAMENTO:")); panel.add(departamento);
    panel.add(new JLabel("DESCRIPCIÓN:")); panel.add(descripcion);
    panel.add(new JLabel("MONTO:")); panel.add(monto);
    panel.add(new JLabel("ESTADO:")); panel.add(estado);

    int result = JOptionPane.showConfirmDialog(null, panel, "Asignar Multa", JOptionPane.OK_CANCEL_OPTION);
    if (result == JOptionPane.OK_OPTION) {
        try {
            double montoValor = Double.parseDouble(monto.getText());

            Multa nueva = new Multa(
                contadorID++,
                placa.getText(),
                fecha.getText(),
                departamento.getText(),
                descripcion.getText(),
                montoValor,
                estado.getText()
            );

            listaMultas.insertarOrdenado(nueva); // Inserta ordenado
            refrescarTabla();                     // Refresca la tabla con nuevo orden

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El monto debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_Asignar_MultaActionPerformed

    private void EscribirBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirBusActionPerformed

    private void Buscar_Placa_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_Placa_1ActionPerformed
        // TODO add your handling code here:
            String placaBuscada = EscribirBus.getText().trim();
    if (placaBuscada.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un número de placa.");
        return;
    }

    Multa resultado = listaMultas.buscarPorPlaca(placaBuscada);

    DefaultTableModel modeloFiltrado = new DefaultTableModel(
        new Object[]{"BOLETA", "PLACA", "FECHA", "DEPARTAMENTO", "DESCRIPCIÓN", "MONTO", "ESTADO"}, 0
    );

    if (resultado != null) {
        modeloFiltrado.addRow(resultado.toArray());
        Tabla_Multa_1.setModel(modeloFiltrado);
    } else {
        JOptionPane.showMessageDialog(this, "No se encontraron registros para la placa ingresada.");
    }
    }//GEN-LAST:event_Buscar_Placa_1ActionPerformed

    private void Ticket_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ticket_1ActionPerformed
        // TODO add your handling code here:
           String idStr = JOptionPane.showInputDialog(this, "Ingrese el número de BOLETA:");
    if (idStr == null || idStr.trim().isEmpty()) return;

    try {
        int id = Integer.parseInt(idStr.trim());
        Nodo actual = listaMultas.cabeza;
        while (actual != null) {
            if (actual.dato.id == id) {
                String ticket = "----- TICKET DE PAGO -----\n"
                        + "BOLETA: " + actual.dato.id + "\n"
                        + "PLACA: " + actual.dato.placa + "\n"
                        + "FECHA: " + actual.dato.fecha + "\n"
                        + "DEPARTAMENTO: " + actual.dato.departamento + "\n"
                        + "DESCRIPCIÓN: " + actual.dato.descripcion + "\n"
                        + "MONTO: Q" + actual.dato.monto + "\n"
                        + "ESTADO: " + actual.dato.estado + "\n"
                        + "---------------------------";
                JOptionPane.showMessageDialog(this, ticket);
                return;
            }
            actual = actual.siguiente;
        }

        JOptionPane.showMessageDialog(this, "No se encontró una multa con ese número de BOLETA.");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Número de BOLETA inválido.");
    }
    }//GEN-LAST:event_Ticket_1ActionPerformed

    private void Eliminar_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_1ActionPerformed
        // TODO add your handling code here:
         String idStr = JOptionPane.showInputDialog(this, "Ingrese el ID que desea eliminar:");
        if (idStr == null || idStr.trim().isEmpty()) return;
        try {
            int id = Integer.parseInt(idStr.trim());
            if (listaMultas.eliminarPorID(id)) {
                JOptionPane.showMessageDialog(this, "Registro eliminado correctamente.");
                refrescarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un registro con ese ID.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
        }
    }//GEN-LAST:event_Eliminar_1ActionPerformed

    private void Descargar_Fich_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Descargar_Fich_1ActionPerformed
        // TODO add your handling code here:
          JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar archivo de multas");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto", "txt"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try (PrintWriter writer = new PrintWriter(new FileWriter(archivo))) {
                Nodo actual = listaMultas.cabeza;
                while (actual != null) {
                    Multa m = actual.dato;
                    writer.println(m.placa + "," + m.fecha + "," + m.departamento + "," + m.descripcion + "," + m.monto);
                    actual = actual.siguiente;
                }
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo.");
            }
        }
    }//GEN-LAST:event_Descargar_Fich_1ActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void Buscar_FchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_FchActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto", "txt"));
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File archivoActual = fileChooser.getSelectedFile();
        listaMultas.limpiar(); // Borra la lista enlazada antes de cargar
        contadorID = 1; // Reinicia el contador de BOLETA

        int lineasMalFormateadas = 0;
        try (BufferedReader reader = new BufferedReader(new FileReader(archivoActual))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] datos = line.split(",");
                if (datos.length == 6) { // Ahora se espera solo 6 campos
                    try {
                        double monto = Double.parseDouble(datos[4].trim());
                        Multa m = new Multa(
                            contadorID++,           // BOLETA generado automáticamente
                            datos[0].trim(),        // PLACA
                            datos[1].trim(),        // FECHA
                            datos[2].trim(),        // DEPARTAMENTO
                            datos[3].trim(),        // DESCRIPCION
                            monto,                  // MONTO
                            datos[5].trim()         // ESTADO
                        );
                        listaMultas.insertarOrdenado(m);
                    } catch (NumberFormatException e) {
                        lineasMalFormateadas++;
                    }
                } else {
                    lineasMalFormateadas++;
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo.");
            return;
        }

        refrescarTabla(); // Este método debe actualizar la JTable con los datos cargados

        if (lineasMalFormateadas > 0) {
            JOptionPane.showMessageDialog(this, 
                "Carga completada con advertencias.\n" + 
                "Líneas ignoradas por formato incorrecto: " + lineasMalFormateadas,
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }
    }//GEN-LAST:event_Buscar_FchActionPerformed

    private void VEHICULOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VEHICULOSActionPerformed
        // TODO add your handling code here:
        Primer_Panel.removeAll();
    Primer_Panel.setLayout(new BorderLayout()); // Ajusta el layout para que PanelVehiculos ocupe todo el espacio

    // Crear instancia del PanelVehiculos
    PanelVehiculos panelVehiculos = new PanelVehiculos();

    // Agregarlo al panel principal
    Primer_Panel.add(panelVehiculos, BorderLayout.CENTER);
    Primer_Panel.revalidate();  // Refrescar la UI
    Primer_Panel.repaint();
    }//GEN-LAST:event_VEHICULOSActionPerformed

    private void TRASPASOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRASPASOSActionPerformed
        // TODO add your handling code here:
            try {
            System.out.println("Botón TRASPASOS presionado");

            // Obtener el contenedor padre (por ejemplo el JFrame)
            java.awt.Container parent = getParent();

            // Asegurar que el contenedor no sea null
            if (parent != null) {
                parent.removeAll(); // Quita todos los componentes actuales
                parent.setLayout(new BorderLayout()); // Asegura un layout adecuado
                parent.add(new PanelTraspaso(), BorderLayout.CENTER); // Agrega el nuevo panel
                parent.revalidate(); // Revalida el nuevo contenido
                parent.repaint();   // Redibuja la interfaz
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo obtener el panel contenedor.");
            }
        } catch (Exception ex) {
            ex.printStackTrace(); // Imprime el error en la consola
            JOptionPane.showMessageDialog(null, "Error al cargar PanelTraspaso: " + ex.getMessage());
        }
    }//GEN-LAST:event_TRASPASOSActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Asignar_Multa;
    private javax.swing.JButton Barra;
    private javax.swing.JButton Buscar_Fch;
    private javax.swing.JButton Buscar_Placa_1;
    private javax.swing.JButton Descargar_Fich_1;
    private javax.swing.JPanel Desplegable;
    private javax.swing.JButton Eliminar_1;
    private javax.swing.JTextField EscribirBus;
    private javax.swing.JButton MULTAS;
    private javax.swing.JButton Nuevo_Doc;
    private javax.swing.JPanel Panel_Llenado_1;
    private javax.swing.JPanel Primer_Panel;
    private javax.swing.JButton RESUMEN;
    private javax.swing.JButton TRASPASOS;
    private javax.swing.JTable Tabla_Multa_1;
    private javax.swing.JButton Ticket_1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel User_Indicator;
    private javax.swing.JButton Usuario;
    private javax.swing.JButton VEHICULOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
